logging:
  level:
    root: WARN
#    root: INFO
    com.example: DEBUG
    org.apache.camel: INFO
    org.springframework: INFO
    logTest: INFO

# to reconfigure the camel servlet context-path mapping to use /api/* instead of /camel/*
camel.servlet.mapping.context-path: /api/*

spring:
  profiles:
    active: debug

app:
  router:
    file:
      input: data/input
      output: data/output

springdoc:
  swagger-ui:
    urls:
      - name: camel api
        url: /api/api-doc
      - name: default api
        url: /v3/api-docs

# rest can also be configured here instead in the CamelRouter class
# rest DSL configuration
#camel.rest.component: servlet
#camel.rest.binding-mode: json
#camel.rest.data-format-property[prettyPrint]: true
#camel.rest.enable-cors: true
#camel.rest.port: ${server.port:8080}
#camel.rest.context-path: /api

# rest DSL api-doc configuration
#camel.rest.api-context-path: /api-doc
#camel.rest.api-property[api.title]: User API
#camel.rest.api-property[api.version]: 1.0.0