logging:
  level:
    root: WARN
#    root: INFO
    com.example: DEBUG
    org.apache.camel: DEBUG
#    org.springframework: DEBUG
    org.springframework: WARN

camel:
  springboot:
    tracing: true
    tracing-standby: true
